# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-13 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '行政区划', 'verbose_name_plural': '行政区划'},
        ),
        migrations.AlterModelTable(
            name='area',
            table='tb_areas',
        ),
    ]
